baseURL = "https://deo.my.id/"
theme = "hugo-deo"
title = "Deo Valiandro. M"
locale = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy", "RSS"]

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 20

[permalinks]
blog = "/p/:slug"

[params]
description = "My Personal Blog"
favicon = "img/favicon.png"

[params.author]
name = "Deo"
email = "deo@duck.com"

[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 3

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
codeFences = true
tabWidth = 4
lineNos = false

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
