baseURL = "https://deo.my.id"
theme = 'hugo-deo'
title = "Deo Valiandro. M"
copyright = "Copyright © 2024, Deo"
languageCode = "en-US"

disableKinds = ["taxonomy", "robotsTXT", "RSS", "term"]
canonifyURLs = true
cleanDestinationDir = true
uglyURLs = false

[params]
  description = "Deo's Blog"
  favicon = "images/favicon.ico"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    linenos = false
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 4
