baseURL = "https://deo.my.id/"
theme = "hugo-deo"
title = "Deo Valiandro. M"
languageCode = "en-US"
disableKinds = ["taxonomy", "RSS", "term"]
enableRobotsTXT = true

[params]
  description = "Deo's Blog"
  favicon = "images/favicon.ico"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    linenos = false
    noClasses = false
    noHl = false
    tabWidth = 4
