baseURL = "https://deo.my.id/"
title = "Deo Valiandro. M"
locale = "en-US"

enableRobotsTXT = true
theme = "hugo-deo"
# disableKinds = ["taxonomy", "RSS"]

[permalinks]
blog = "/p/:slug"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
pageRef = "/tags/"
weight = 30

[taxonomies]
tag = "tags"
category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
name = "Deo"
author = "Deo"
email = "deo@duck.com"

description = "My Personal Blog"
favicon = "img/favicon.png"

footer = "©️ 2026 - Deo. 🌱 with ❤️‍🔥 from 🌏"

[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 3

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
codeFences = true
tabWidth = 4
lineNos = false
