project:
  render:
    - "*.qmd"
  type: default
  output-dir: ../content/blog   # output langsung ke folder Hugo

format:
  hugo-md:
    output-ext: md
    wrap: none
    # Arahkan semua gambar ke static Hugo
    fig-path: ../../static/images/posts/

execute:
  freeze: auto